### ISSUE TITLE
apply for elevate?

### ISSUE THREAD

**Issue by micrem73** [LitoMore/twe#22]
After installing and configuring on macos, running "twe" shows "Fetching" then nothing appear. 
Running "twe hi" to update the status i get:
"errors":[{"message":"You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve","code":453}]}

I dug into twitter help but sounds there's no elevate plan anymore, and the free should be enough to post.
Any idea'

**Comment by LitoMore** [comment]
@micrem73 Thank you for reporting this.

It's because its API module [Twii](https://github.com/LitoMore/twii) uses Twitter's API v1.1 by default.

See https://github.com/LitoMore/twii/blob/89841eaabda4c3ab0daa23229e8bb6d36e3dc155/index.js#L15.

I will try to update it to v2.

**Comment by LitoMore** [comment]
Hi @micrem73 I just fixed the `fetching` issue. And the API is still using API v1. There is no need to upgrade to v2 for now.

But we can consider migrating to API v2 when we have more high-level features.

**Comment by micrem73** [comment]
I rerun the install command.
Now on running "twe" i get:

mc@MicMac ~ % twe
/Users/mc/.nvm/versions/node/v16.13.0/lib/node_modules/twe/node_modules/conf/dist/source/index.js:90
                throw new Error('Project name could not be inferred. Please specify the `projectName` option.');
                      ^

Error: Project name could not be inferred. Please specify the `projectName` option.
    at new Conf (/Users/mc/.nvm/versions/node/v16.13.0/lib/node_modules/twe/node_modules/conf/dist/source/index.js:90:23)
    at file:///Users/mc/.nvm/versions/node/v16.13.0/lib/node_modules/twe/src/settings.js:22:14
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

**Comment by LitoMore** [comment]
OK, let me check.

**Comment by LitoMore** [comment]
@micrem73 This should be fixed. Please upgrade with:

```sh
npm i -g twe@latest
```

**Comment by LitoMore** [comment]
BTW, feel free to share your thoughts about this project.

I'm thinking about spending more time on this project and would like to gather some user feedback.

Thank you.

**Comment by micrem73** [comment]
Thanks for your prompt support.
Now the previous error is fixed running "twe", but this other message appears:
✖ [{"message":"You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product","code":453}]

**Comment by micrem73** [comment]
Here I am about your request for user feedback.
I installed and tried soooo many CLI twitter command, but none of them worked. I think API changes impacted every single one. I appreciated easiness of install and configuration process of twe, compared to other solutions. Your support also is quick. If you manage this to work, well twe would be the only working solution out there, to my knowledge.
Cheers

**Comment by LitoMore** [comment]
@micrem73 You need to go to Twitter Developer Portal and re-created an Elevated app.

Then you will get new tokens there.

<img width="1216" alt="2023-06-05 at 19 07 56@2x" src="https://github.com/LitoMore/twe/assets/8186898/a4afe752-76ba-4c02-9771-0f7ac3370492">

I will create a documentation to tell users how to create their own tokens later days.

**Comment by micrem73** [comment]
Thanks. I deleted app and project, and recreate it. I see no ways to create it differently rather a "free" profile.
<img width="751" alt="Schermata 2023-06-05 alle 21 19 52" src="https://github.com/LitoMore/twe/assets/1117389/8a8a3e0a-6bdb-42e7-96f4-069f7ec5baa3">

**Comment by LitoMore** [comment]
https://developer.twitter.com/en/portal/products/elevated

It is link working for you? You need to regenerate tokens once your app upgraded to Elevated.

**Comment by micrem73** [comment]
I still fell into this loop time ago. This link redirect me to https://developer.twitter.com/en/portal/products where no mention of elevated is present. I'm aware now we are shifting to Twitter support rather than your sw, but all this confusion from them really sucks.
